-- MySQL Script generated by MySQL Workbench
-- Sun Jul  9 18:38:01 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projetoBd
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `projetoBd` ;

-- -----------------------------------------------------
-- Schema projetoBd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetoBd` DEFAULT CHARACTER SET utf8 ;
USE `projetoBd` ;

-- -----------------------------------------------------
-- Table `projetoBd`.`departamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetoBd`.`departamentos` ;

CREATE TABLE IF NOT EXISTS `projetoBd`.`departamentos` (
  `codDepartamento` INT NOT NULL,
  `nome` VARCHAR(150) NULL,
  PRIMARY KEY (`codDepartamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoBd`.`disciplinas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetoBd`.`disciplinas` ;

CREATE TABLE IF NOT EXISTS `projetoBd`.`disciplinas` (
  `codDisciplina` VARCHAR(13) NOT NULL,
  `nome` VARCHAR(150) NULL,
  `codDepartamento` INT NOT NULL,
  PRIMARY KEY (`codDisciplina`),
  INDEX `fk_disciplinas_departamentos_idx` (`codDepartamento` ASC) VISIBLE,
  CONSTRAINT `fk_disciplinas_departamentos`
    FOREIGN KEY (`codDepartamento`)
    REFERENCES `projetoBd`.`departamentos` (`codDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoBd`.`turmas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetoBd`.`turmas` ;

CREATE TABLE IF NOT EXISTS `projetoBd`.`turmas` (
  `idTurma` INT NOT NULL,
  `departamentos_codDepartamento` INT NOT NULL,
  `disciplinas_codDisciplina` VARCHAR(13) NOT NULL,
  `turma` VARCHAR(5) NULL,
  `periodo` VARCHAR(6) NULL,
  `professor` VARCHAR(100) NULL,
  `horario` VARCHAR(150) NULL,
  `vagasOcupadas` INT NULL,
  `totalVagas` INT NULL,
  `local` VARCHAR(75) NULL,
  PRIMARY KEY (`idTurma`, `departamentos_codDepartamento`, `disciplinas_codDisciplina`),
  INDEX `fk_departamentos_has_disciplinas_disciplinas1_idx` (`disciplinas_codDisciplina` ASC) VISIBLE,
  INDEX `fk_departamentos_has_disciplinas_departamentos1_idx` (`departamentos_codDepartamento` ASC) VISIBLE,
  CONSTRAINT `fk_departamentos_has_disciplinas_departamentos1`
    FOREIGN KEY (`departamentos_codDepartamento`)
    REFERENCES `projetoBd`.`departamentos` (`codDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_departamentos_has_disciplinas_disciplinas1`
    FOREIGN KEY (`disciplinas_codDisciplina`)
    REFERENCES `projetoBd`.`disciplinas` (`codDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
