---

version: '3.7'

services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - '3306:3306'
  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile